[package]
name = "rolldown_deno"
version = "0.1.0"

edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "rolldown_deno"
path = "main.rs"

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
deno_cache_dir = { version = "0.22.1", features = ["sync"] }
deno_config = { version = "0.54.2", features = ["workspace", "sync"] }
deno_error = "0.6.0"
deno_graph = { version = "0.94.2", default-features = false }
deno_npm_cache = { path = "../../../deno/resolvers/npm_cache" }
deno_npm_installer = { path = "../../../deno/resolvers/npm_installer" }
deno_path_util = "0.3.3"
deno_resolver = { path = "../../../deno/resolvers/deno", features = ["graph", "sync"] }
deno_semver = "0.8.0"
node_resolver = { path = "../../../deno/resolvers/node", features = ["sync"] }
oxc.workspace = true
reqwest = "0.12.9"
rolldown = { path = "../rolldown" }
rolldown_common = { path = "../rolldown_common" }
rolldown_plugin = { path = "../rolldown_plugin" }
rolldown_testing = { path = "../rolldown_testing" }
sugar_path.workspace = true
sys_traits = { version = "0.1.12", features = ["real", "libc", "winapi", "getrandom"] }
tokio.workspace = true
url.workspace = true
